build:
  tests:
    before:
      - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - sudo npm install -g --unsafe-perm csso-cli@2
      - sudo npm install -g requirejs
    override:
      - command: './bin/phing unit'
        coverage:
          file: 'test/coverage.xml'
          format: 'php-clover'
