language: php
php:
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
  
before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g csso-cli
    
install:
  - composer self-update
  - composer install

script:
  - ./bin/phing unit
