language: php
php:
  - '7.0'
  - '7.1'
  - hhvm
  - nightly
  
before_install:
  - sudo apt-get install nodejs
  - sudo npm install -g csso-cli
    
install:
  - composer self-update
  - composer install

script:
  - ./bin/phing unit
