language: php

matrix:
  include:
    - dist: focal
      php:
          - '7.4'
          - '8.0'

before_install:
  - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g csso-cli
  - sudo npm install -g requirejs
  - php -r 'print_r(SQLite3::version());'

install:
  - npm install -g csso
  - pecl install inotify
  - composer self-update
  - composer install

script:
  - ./bin/phing unit
