language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
  
before_install:
  - sudo npm install -g csso-cli
    
install:
  - composer self-update
  - composer install

script:
  - ./bin/phing unit
