language: php
php:
  - '7.3'
  - '7.4'

before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -g csso-cli
  - sudo npm install -g require.js

install:
  - npm install -g csso
  - composer self-update
  - composer install

script:
  - ./bin/phing unit
