/**
 * Selects all resources files.
 *
 * @type rows
 */
select rsr.rsr_id
,      rsr.rsr_path
,      rsr.rsr_mtime
,      rsr.rsr_depth
,      rsr.rsr_content
,      rsr.rsr_content_optimized
,      rsr.rsr_uri_optimized

,      rtp.rtp_id
,      rtp.rtp_regex
,      rtp.rtp_name
,      rtp.rtp_class
from   ABC_RESOURCE      rsr
join   ABC_RESOURCE_TYPE rtp  on  rtp.rtp_id = rsr.rtp_id
order by rsr.rsr_path
